/*
 * @Description:
 * @Author: alysalu@tencent.com
 * @Date: 2022-03-02 10:33:03
 */
// There is an array generated by a rule.
// The first item is 1. If k is in the array, then k*3 +1 and k*2+1 are in the array.
// The array is sorted. There are no duplicate values.
// Please write a function that accepts an input N. It should return the index N of the array.
// For example [1, 3, 4, 7, 9, 10, 13, 15, 19, 21, 22, 27, ...] n=10, return 22
function pushK(arr, k) {
  if (arr.indexOf(k) < 0) {
    arr.push(k);
  }
}

function getNumberFromTheArray(N) {
  if (N === 0) {
    return 1;
  }
  // const set = new Set();
  const arrSet = [1];

  for (let i = 0;i < arrSet.length ;i++) {
    const k  = arrSet[i];
    pushK(arrSet, k);
    pushK(arrSet, 2 * k + 1);
    pushK(arrSet, 3 * k + 1);
    if (arrSet.length >  3 * N) break;
  }
  const arr = arrSet.sort((a, b) => a - b);
  return arr[N];
}


console.log(getNumberFromTheArray(5)); // 10;
console.log(getNumberFromTheArray(10)); // 22;
console.log(getNumberFromTheArray(1000)); // 447;
